# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170626_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
